[package]
name = "quickwit-common"
version = "0.3.1"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later" # For a commercial, license, contact hello@quickwit.io
description = "Util crate of quickwit"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = "1.0"
colored = "2"
env_logger = "0.9"
home = "0.5.3"
itertools = "0.10.3"
num_cpus = "1"
once_cell = "1"
pnet = { version = "0.31.0", features = [ "std" ] }
prometheus = { version = "0.13", features = ["process"] }
rand = "0.8"
regex = "1"
serde = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.29"
warp = "0.3"

[features]
testsuite = []

[dev-dependencies]
serde_json = "1.0"
tempfile = "3"
