# Headless service for indexer stateful set
apiVersion: v1
kind: Service
metadata:
  name: indexers
  labels:
    app: indexers
spec:
  clusterIP: None
  ports:
    - port: 7280
      name: rest
    - port: 7281
      name: grpc
  selector:
    app: quickwit
    service: indexer
